-- MySQL Script generated by MySQL Workbench
-- 11/10/18 11:29:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`materia` (
  `idmateria` INT NOT NULL,
  `nombre_materia` VARCHAR(45) NULL,
  PRIMARY KEY (`idmateria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estudiante` (
  `id_estudiante` INT NOT NULL,
  `nombres_estudiante` VARCHAR(45) NULL,
  `apellidos_estudiante` VARCHAR(45) NULL,
  `correo_estudiante` VARCHAR(45) NULL,
  `telefono_estudiante` VARCHAR(45) NULL,
  PRIMARY KEY (`id_estudiante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`nota` (
  `id_nota` INT NOT NULL,
  `calificacion` VARCHAR(45) NOT NULL,
  `id_materia` INT NOT NULL,
  `id_estudiante` INT NOT NULL,
  PRIMARY KEY (`id_nota`),
  INDEX `fk_nota_materia_idx` (`id_materia` ASC),
  INDEX `fk_nota_estudiante1_idx` (`id_estudiante` ASC),
  CONSTRAINT `fk_nota_materia`
    FOREIGN KEY (`id_materia`)
    REFERENCES `mydb`.`materia` (`idmateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nota_estudiante1`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `mydb`.`estudiante` (`id_estudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prueba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prueba` (
  `id_prueba` INT NOT NULL,
  `nombre_prueba` VARCHAR(45) NULL,
  `cant_pregunta_prueba` VARCHAR(45) NULL,
  `tiempo_prueba` VARCHAR(45) NULL,
  PRIMARY KEY (`id_prueba`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`materia_prueba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`materia_prueba` (
  `id_mat_prueb` INT NOT NULL,
  `materia_idmateria` INT NOT NULL,
  `prueba_id_prueba` INT NOT NULL,
  PRIMARY KEY (`id_mat_prueb`),
  INDEX `fk_materia_prueba_materia1_idx` (`materia_idmateria` ASC),
  INDEX `fk_materia_prueba_prueba1_idx` (`prueba_id_prueba` ASC),
  CONSTRAINT `fk_materia_prueba_materia1`
    FOREIGN KEY (`materia_idmateria`)
    REFERENCES `mydb`.`materia` (`idmateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materia_prueba_prueba1`
    FOREIGN KEY (`prueba_id_prueba`)
    REFERENCES `mydb`.`prueba` (`id_prueba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`grado` (
  `id_grado` INT NOT NULL,
  `nombre_grado` VARCHAR(45) NULL,
  PRIMARY KEY (`id_grado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` INT NOT NULL,
  `login_usuario` VARCHAR(45) NULL,
  `password_usuario` VARCHAR(45) NULL,
  `tipo_usuario` VARCHAR(45) NULL,
  `id_estudiante` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuario_estudiante1_idx` (`id_estudiante` ASC),
  CONSTRAINT `fk_usuario_estudiante1`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `mydb`.`estudiante` (`id_estudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`resultado_saber_once`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resultado_saber_once` (
  `id_resultado_saber_once` INT NOT NULL,
  `calificacion_saber_once` VARCHAR(45) NULL,
  `id_estudiante` INT NOT NULL,
  `id_prueba` INT NOT NULL,
  PRIMARY KEY (`id_resultado_saber_once`),
  INDEX `fk_resultado_saber_once_estudiante1_idx` (`id_estudiante` ASC),
  INDEX `fk_resultado_saber_once_prueba1_idx` (`id_prueba` ASC),
  CONSTRAINT `fk_resultado_saber_once_estudiante1`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `mydb`.`estudiante` (`id_estudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resultado_saber_once_prueba1`
    FOREIGN KEY (`id_prueba`)
    REFERENCES `mydb`.`prueba` (`id_prueba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`periodo_academico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`periodo_academico` (
  `id_periodo_academico` INT NOT NULL,
  `periodo_academico` VARCHAR(45) NULL,
  PRIMARY KEY (`id_periodo_academico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`materia_grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`materia_grado` (
  `id_materia_grado` INT NOT NULL,
  `id_materia` INT NOT NULL,
  `id_grado` INT NOT NULL,
  PRIMARY KEY (`id_materia_grado`),
  INDEX `fk_materia_grado_materia1_idx` (`id_materia` ASC),
  INDEX `fk_materia_grado_grado1_idx` (`id_grado` ASC),
  CONSTRAINT `fk_materia_grado_materia1`
    FOREIGN KEY (`id_materia`)
    REFERENCES `mydb`.`materia` (`idmateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materia_grado_grado1`
    FOREIGN KEY (`id_grado`)
    REFERENCES `mydb`.`grado` (`id_grado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grado_periodo_academico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`grado_periodo_academico` (
  `id_grado_per_acad` INT NOT NULL,
  `periodo_academico_id_periodo_academico` INT NOT NULL,
  `grado_id_grado` INT NOT NULL,
  PRIMARY KEY (`id_grado_per_acad`),
  INDEX `fk_grado_periodo_academico_periodo_academico1_idx` (`periodo_academico_id_periodo_academico` ASC),
  INDEX `fk_grado_periodo_academico_grado1_idx` (`grado_id_grado` ASC),
  CONSTRAINT `fk_grado_periodo_academico_periodo_academico1`
    FOREIGN KEY (`periodo_academico_id_periodo_academico`)
    REFERENCES `mydb`.`periodo_academico` (`id_periodo_academico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grado_periodo_academico_grado1`
    FOREIGN KEY (`grado_id_grado`)
    REFERENCES `mydb`.`grado` (`id_grado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
